version: '3'

services:
    php:
        build:
            context: docker/php
        depends_on:
            - clickhouse
        environment:
            HISTFILE: /root/history/.zsh_history
        volumes:
            - ./:/var/www/html
            - php_socket:/var/run/php
            - php_history:/root/history

    nginx:
        image: nginx:1.24-alpine3.17
        depends_on:
            - php
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - .:/var/www/html:ro
            - php_socket:/var/run/php
        ports:
            - '8080:80'

    clickhouse:
        image: clickhouse/clickhouse-server:22.8
        container_name: "clickhouse"
        ports:
            - "8123:8123"

volumes:
    php_history: ~
    php_socket: ~
